spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://zatch-database-dev.cvwoswmfbxnp.ap-northeast-2.rds.amazonaws.com/zatch
    username: root
    password: zatchServer777!

  # swagger 적용 시 path문제 해결을 위한 설정
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
