spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://zatch-database.ctnnga0s146x.ap-northeast-2.rds.amazonaws.com/zatch
    username: root
    password: woclaocl01

  jwt:
    secret: zatch_server_jwt_secret_key_1234567890
  # swagger 적용 시 path문제 해결을 위한 설정
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  servlet:
    session:
      cookie:
        http-only: true
        secure: true
        same-site: none
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-type: PKCS12
#    key-store-password: zatch
#  http2:
#    enabled: true