spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/zatch
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # swagger 적용 시 path문제 해결을 위한 설정
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
